# Generated by Django 4.1.1 on 2022-09-24 23:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_music_release_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='music',
            name='likes',
        ),
    ]
