# Generated by Django 4.1.1 on 2022-10-01 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0004_music_likes'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Music',
            new_name='Song',
        ),
    ]
